/**
 * Amendment Applier Tests
 *
 * Tests for checkAmendmentStatus, applyAmendment, and related functions from
 * src/core/amend/amendment-applier.ts
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fs } from 'fs';
import path from 'path';
import os from 'os';
import { checkAmendmentStatus, applyAmendment } from '../../../src/core/amend/amendment-applier.js';
import type { AmendmentRecord, TasksRollingPlan } from '../../../src/core/amend/types.js';

async function createTempChangeDir(): Promise<string> {
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'openspec-applier-test-'));

  await fs.writeFile(path.join(tmpDir, 'proposal.md'), '# Proposal\n\n## What Changes\n');
  await fs.writeFile(path.join(tmpDir, 'design.md'), '# Design\n\n## Technical Approach\n');
  await fs.writeFile(path.join(tmpDir, 'tasks.md'), `# Tasks\n\n## 1. Setup\n\n- [x] 1.1 Task one\n- [ ] 1.2 Task two\n`);

  const specsDir = path.join(tmpDir, 'specs', 'auth');
  await fs.mkdir(specsDir, { recursive: true });
  await fs.writeFile(path.join(specsDir, 'spec.md'), '## Requirements\n');

  return tmpDir;
}

async function cleanupDir(dir: string): Promise<void> {
  await fs.rm(dir, { recursive: true, force: true });
}

const CONFIRMED_AMENDMENT_MD = `# Amendment v1: test-change

## Metadata
- **Version**: v1
- **Created**: 2025-01-24T14:30:00Z
- **Amendment Type**: design-issue
- **Status**: CONFIRMED
- **Reason**: Switch from WebSocket to SSE
- **Triggered By**: Task 1.3 implementation

## Summary
Changed from WebSocket to SSE.

## Tasks Rolling Plan

### Rollback Tasks (need to undo completed work)
| Task ID | Description | Rollback Action | Rollback Code |
|---------|-------------|-----------------|---------------|
| 1.1 | Task one | Remove code | Files |

### Restack Tasks (reorder/modify pending tasks)
| Task ID | Original | Modified | Reason |
|---------|----------|----------|--------|
| 1.2 | Task two | Task two updated | Switch to SSE |

### Append Tasks (new tasks to add)
| Task ID | Description | Section | After Task |
|---------|-------------|---------|------------|
| new.1 | New task | 2 | 1.2 |

*Generated by OpenSpec Amend Workflow | Status: CONFIRMED*
`;

describe('AmendmentApplier', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await createTempChangeDir();
  });

  afterEach(async () => {
    await cleanupDir(tmpDir);
  });

  describe('checkAmendmentStatus', () => {
    it('should return NONE when no amendment.md exists', async () => {
      const result = await checkAmendmentStatus(tmpDir);

      expect(result.status).toBe('NONE');
      expect(result.version).toBeUndefined();
    });

    it('should return DRAFT when amendment.md has DRAFT status', async () => {
      const draftContent = CONFIRMED_AMENDMENT_MD.replace('CONFIRMED', 'DRAFT');
      await fs.writeFile(path.join(tmpDir, 'amendment.md'), draftContent);

      const result = await checkAmendmentStatus(tmpDir);

      expect(result.status).toBe('DRAFT');
      expect(result.version).toBe(1);
    });

    it('should return CONFIRMED when amendment.md has CONFIRMED status', async () => {
      await fs.writeFile(path.join(tmpDir, 'amendment.md'), CONFIRMED_AMENDMENT_MD);

      const result = await checkAmendmentStatus(tmpDir);

      expect(result.status).toBe('CONFIRMED');
      expect(result.version).toBe(1);
    });

    it('should return APPLIED when amendment.md has APPLIED status', async () => {
      const appliedContent = CONFIRMED_AMENDMENT_MD.replace('CONFIRMED', 'APPLIED');
      await fs.writeFile(path.join(tmpDir, 'amendment.md'), appliedContent);

      const result = await checkAmendmentStatus(tmpDir);

      expect(result.status).toBe('APPLIED');
    });

    it('should treat legacy amendment.md without status as CONFIRMED', async () => {
      const legacyContent = `# Amendment: test-change\n\n## Changes\n\nSome changes.\n`;
      await fs.writeFile(path.join(tmpDir, 'amendment.md'), legacyContent);

      const result = await checkAmendmentStatus(tmpDir);

      // Legacy without status field → treated as CONFIRMED for backward compat
      expect(result.status).toBe('CONFIRMED');
    });
  });

  describe('applyAmendment', () => {
    it('should return success with NONE status when no amendment exists', async () => {
      const result = await applyAmendment(tmpDir);

      expect(result.success).toBe(true);
      expect(result.amendmentStatus).toBe('NONE');
      expect(result.artifactsModified).toEqual([]);
      expect(result.tasksRollingApplied).toBe(false);
    });

    it('should fail with DRAFT status amendment', async () => {
      const draftContent = CONFIRMED_AMENDMENT_MD.replace('CONFIRMED', 'DRAFT');
      await fs.writeFile(path.join(tmpDir, 'amendment.md'), draftContent);

      const result = await applyAmendment(tmpDir);

      expect(result.success).toBe(false);
      expect(result.amendmentStatus).toBe('DRAFT');
      expect(result.error).toContain('DRAFT');
    });

    it('should skip with APPLIED status amendment', async () => {
      const appliedContent = CONFIRMED_AMENDMENT_MD.replace('CONFIRMED', 'APPLIED');
      await fs.writeFile(path.join(tmpDir, 'amendment.md'), appliedContent);

      const result = await applyAmendment(tmpDir);

      expect(result.success).toBe(true);
      expect(result.amendmentStatus).toBe('APPLIED');
      expect(result.artifactsModified).toEqual([]);
      expect(result.tasksRollingApplied).toBe(false);
    });

    it('should apply CONFIRMED amendment with state file', async () => {
      await fs.writeFile(path.join(tmpDir, 'amendment.md'), CONFIRMED_AMENDMENT_MD);

      // Create state file with structured changes
      const state = {
        changeName: 'test-change',
        timestamp: '2025-01-24T14:30:00Z',
        amendmentType: 'design-issue',
        status: 'CONFIRMED',
        changes: {
          modificationLogic: {
            affectedArtifacts: [
              { artifact: 'design', action: 'MODIFY', priority: 'P0', reason: 'Switch to SSE' },
              { artifact: 'proposal', action: 'MODIFY', priority: 'P2', reason: 'Update scope' }
            ],
            modificationOrder: ['design', 'proposal']
          },
          tasksRolling: {
            rollback: [{ id: '1.1', description: 'Task one', rollbackAction: 'Remove code', rollbackCode: 'Files' }],
            restack: [{ id: '1.2', originalDescription: 'Task two', newDescription: 'Task two updated', reason: 'Switch to SSE' }],
            append: [{ id: 'new.1', description: 'New task', section: '2', afterTask: '1.2' }],
            deprecate: [],
            newSequence: []
          }
        }
      };
      await fs.writeFile(path.join(tmpDir, '.amendment-state.json'), JSON.stringify(state));

      const result = await applyAmendment(tmpDir);

      expect(result.success).toBe(true);
      expect(result.amendmentStatus).toBe('APPLIED');
      expect(result.artifactsModified.length).toBeGreaterThan(0);
      expect(result.tasksRollingApplied).toBe(true);

      // Check amendment.md was updated to APPLIED
      const updatedContent = await fs.readFile(path.join(tmpDir, 'amendment.md'), 'utf-8');
      expect(updatedContent).toContain('APPLIED');

      // Check state file was updated
      const updatedState = JSON.parse(await fs.readFile(path.join(tmpDir, '.amendment-state.json'), 'utf-8'));
      expect(updatedState.status).toBe('APPLIED');
    });

    it('should apply CONFIRMED amendment parsing from amendment.md (no state file)', async () => {
      await fs.writeFile(path.join(tmpDir, 'amendment.md'), CONFIRMED_AMENDMENT_MD);

      // No .amendment-state.json — should parse from amendment.md as fallback
      const result = await applyAmendment(tmpDir);

      expect(result.success).toBe(true);
      expect(result.amendmentStatus).toBe('APPLIED');
      // Since fallback parsing doesn't have structured changes, tasksRolling won't be applied
    });

    it('should annotate artifact files with version comments', async () => {
      await fs.writeFile(path.join(tmpDir, 'amendment.md'), CONFIRMED_AMENDMENT_MD);

      const state = {
        changeName: 'test-change',
        timestamp: '2025-01-24T14:30:00Z',
        amendmentType: 'design-issue',
        status: 'CONFIRMED',
        changes: {
          modificationLogic: {
            affectedArtifacts: [
              { artifact: 'proposal', action: 'MODIFY', priority: 'P2', reason: 'Update scope' },
              { artifact: 'design', action: 'MODIFY', priority: 'P0', reason: 'Switch to SSE' }
            ],
            modificationOrder: ['design', 'proposal']
          }
        }
      };
      await fs.writeFile(path.join(tmpDir, '.amendment-state.json'), JSON.stringify(state));

      const result = await applyAmendment(tmpDir);

      // Check proposal.md was annotated
      const proposalContent = await fs.readFile(path.join(tmpDir, 'proposal.md'), 'utf-8');
      expect(proposalContent).toContain('<!-- Amendment v1:');

      // Check design.md was annotated
      const designContent = await fs.readFile(path.join(tmpDir, 'design.md'), 'utf-8');
      expect(designContent).toContain('<!-- Amendment v1:');
    });
  });
});